general:
  angular_scale: 1.0
  csv_path: /ros_ws/src/ros1_vive_controller/data/
  frame_id: ci/world
  left_gripper_topic: /dxl_input/gripper_left
  left_marker_topic: /dxl_input/marker_left
  left_position_topic: /dxl_input/pos_left
  linear_scale: 1.0
  move_base: false
  move_base_angular_topic: /dxl_input/angular
  move_base_linear_x_topic: /dxl_input/linear_x
  move_base_linear_y_topic: /dxl_input/linear_y
  node_name: vice_controllers
  publish_markers: true
  rate: 100
  right_gripper_topic: /dxl_input/gripper_right
  right_marker_topic: /dxl_input/marker_right
  right_position_topic: /dxl_input/pos_right
  robot: tiago
  space_scale: 1.0
  talos_right_gripper_topic: /dxl_input/gripper
  talos_right_position_topic: /dxl_input/pose
  use_left_controller: false
  use_right_controller: true
  workspace_limit: 0.0
  z_threshold: 1.8
htc_vive:
  controller_1:
    name: right_controller
    serial: LHR-9ABF6D66
    type: controller
  controller_2:
    name: left_controller
    serial: LHR-21C1BC92
    type: controller
  tracker_1:
    name: head_tracker
    serial: LHR-631A5257
    type: tracker
one_euro_filter:
  beta: 0.1
  cutoff: 1.0
  mincutoff: 1.0
workspace:
  x_max: -0.43
  x_min: -1.24
  y_max: 0.45
  y_min: -0.95
  z_max: -0.24
  z_min: -1.35
