general:
  frame_id: ci/world
  left_gripper_topic: /dxl_input/gripper_right
  left_marker_topic: /dxl_input/marker_right
  left_position_topic: /dxl_input/pos_right
  node_name: vice_controllers
  publish_markers: true
  rate: 50
  right_gripper_topic: /dxl_input/gripper_left
  right_marker_topic: /dxl_input/marker_left
  right_position_topic: /dxl_input/pos_left
  space_scale: 1.0
  use_left_controller: true
  use_right_controller: true
  workspace_limit: 0.2
htc_vive:
  controller_1:
    name: right_controller
    serial: LHR-9ABF6D66
    type: controller
  controller_2:
    name: left_controller
    serial: LHR-21C1BC92
    type: controller
  tracker:
    name: head_tracker
    serial: null
    type: tracker
kalman_filter:
  frequency: 50
  measurement_dim: 6
  state_dim: 6
workspace:
  x_max: -0.61
  x_min: -1.47
  y_max: 0.47
  y_min: -0.71
  z_max: 0.71
  z_min: -0.46
