general:
  angular_scale: 1.0
  csv_path: /ros_ws/src/ros1_vive_controller/data/
  frame_id: world
  left_gripper_topic: /vive/left/gripper
  left_marker_topic: /vive/left/marker
  left_position_topic: /vive/left/pose
  linear_scale: 1.0
  link_name: world
  move_base: false
  move_base_angular_topic: /vive/base/angular
  move_base_linear_x_topic: /vive/base/linear_x
  move_base_linear_y_topic: /vive/base/linear_y
  node_name: vive_controllers
  publish_markers: true
  push_to_talk_topic: /vive/push_to_talk
  rate: 90
  reset_position_topic: /streamdeck/reset_initial_state
  right_gripper_topic: /vive/right/gripper
  right_marker_topic: /vive/right/marker
  right_position_topic: /vive/right/pose
  robot_name: tiago
  use_left_controller: true
  use_right_controller: true
  workspace_limit: 0.05
  z_threshold: 3.0
htc_vive:
  controller_left:
    name: left_controller
    serial: LHR-97752221
    type: controller
  controller_right:
    name: right_controller
    serial: LHR-4BB3817E
    type: controller
  tracking_reference:
    name: master
    serial: LHB-DFA5BD2C
    type: tracking_reference
offset:
  franka:
    x: 0.35
    y: -0.05
    z: 0.5
  g1:
    left:
      x: -0.04
      y: 0.26
      z: 0.53
    right:
      x: -0.04
      y: -0.26
      z: 0.53
  tiago:
    left:
      x: 0.06
      y: 0.35
      z: 0.53
    right:
      x: 0.06
      y: -0.35
      z: 0.53
one_euro_filter:
  beta: 0.1
  dcutoff: 1.0
  mincutoff: 1.0
workspace:
  x_max: -0.43
  x_min: -2.6
  y_max: 1.13
  y_min: -1.25
  z_max: 0.66
  z_min: -1.58
