general:
  robot_name: tiago # change this to load specific offsets (look at offset section)
  node_name: vive_controllers
  frame_id: world
  link_name: world
  rate: 90

  # Generic Topics
  right_position_topic: /vive/right/pose
  right_gripper_topic: /vive/right/gripper
  left_position_topic: /vive/left/pose
  left_gripper_topic: /vive/left/gripper

  # Extras
  push_to_talk_topic: /vive/push_to_talk
  reset_position_topic: /streamdeck/reset_initial_state
  publish_markers: true
  right_marker_topic: /vive/right/marker
  left_marker_topic: /vive/left/marker

  # Worskspace related
  workspace_limit: 0.05
  z_threshold: 3.0
  csv_path: /ros_ws/src/ros1_vive_controller/data/ # workspace path

  # Base movement (optional)
  move_base: false
  move_base_angular_topic: /vive/base/angular
  move_base_linear_x_topic: /vive/base/linear_x
  move_base_linear_y_topic: /vive/base/linear_y
  linear_scale: 1.0
  angular_scale: 1.0
  use_left_controller: true
  use_right_controller: true

# Hardware Config
htc_vive:
  controller_right:
    name: right_controller
    serial: LHR-4BB3817E
    type: controller
  controller_left:
    name: left_controller
    serial: LHR-97752221
    type: controller
  tracking_reference:
    name: master
    serial: LHB-DFA5BD2C
    type: tracking_reference

# Robot Offsets
# TODO: check if this could be replaced by waiting for topic
# regarding the current eef positions of the robot  to avoid jumps, and hardcoded values
offset:
  franka:
    x: 0.35
    y: -0.05
    z: 0.5
  g1:
    left:
      x: -0.04
      y: 0.26
      z: 0.53
    right:
      x: -0.04
      y: -0.26
      z: 0.53
  tiago:
    left:
      x: 0.06
      y: 0.35
      z: 0.53
    right:
      x: 0.06
      y: -0.35
      z: 0.53
one_euro_filter:
  beta: 0.1
  dcutoff: 1.0
  mincutoff: 1.0
workspace:
  x_max: -0.66
  x_min: -2.12
  y_max: 1.19
  y_min: -0.1
  z_max: -0.37
  z_min: -1.58
