/**:
  ros__parameters:
    workspace:
      x_max: -0.664
      x_min: -1.71
      y_max: 0.5
      y_min: -0.214
      z_max: -0.089
      z_min: -0.479
/vive/**:
  ros__parameters:
    filter:
      beta: 0.01
      dcutoff: 1.0
      mincutoff: 1.0
    frame_id: vive_world
    htc_vive:
      tracking_reference: LHB-DFA5BD2C
    workspace:
      padding: 0.15
      x_max: 10.5
      x_min: -10.5
      y_max: 10.5
      y_min: -10.5
      z_max: 20.2
      z_min: -20.2
